---
- project:
    check:
      jobs:
        - python-builder-build-container-image
        - python-builder-test-container-image
    gate:
      jobs:
        - python-builder-build-container-image
        - python-builder-test-container-image
    post:
      jobs:
        - python-builder-upload-container-image:
            vars:
              upload_container_image_promote: false
    periodic:
      jobs:
        - python-builder-upload-container-image:
            vars:
              upload_container_image_promote: false
